// Auto-generated facade for ecldata7.ecl by tools/th08/ecl.
// Do not edit directly; change the translator and run `npm run ecl:th08`.
//
// 89 subs, 1 timeline(s), 44 spell cards
// declared by op 122, 20 of them final spells per g_LastSpellNumbers.

import type { StageScript } from '../StageScript';
import * as SCRIPTS from './scripts';
import { ECL_FILE } from './waves';

export const STAGE6B_SCRIPT: StageScript = {
  route: 'stage6b',
  source: 'ecldata7.ecl',
  subCount: 89,
  timelineCount: 1,
  cards: [
    {
      sub: 19,
      id: 147,
      name: '薬符「壺中の大銀河」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 19,
      id: 148,
      name: '薬符「壺中の大銀河」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 19,
      id: 149,
      name: '薬符「壺中の大銀河」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 19,
      id: 150,
      name: '薬符「壺中の大銀河」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 50,
      id: 151,
      name: '難題「龍の頸の玉  -五色の弾丸-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 50,
      id: 152,
      name: '難題「龍の頸の玉  -五色の弾丸-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 50,
      id: 153,
      name: '神宝「ブリリアントドラゴンバレッタ」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 50,
      id: 154,
      name: '神宝「ブリリアントドラゴンバレッタ」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 55,
      id: 155,
      name: '難題「仏の御石の鉢  -砕けぬ意思-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 55,
      id: 156,
      name: '難題「仏の御石の鉢  -砕けぬ意思-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 55,
      id: 157,
      name: '神宝「ブディストダイアモンド」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 55,
      id: 158,
      name: '神宝「ブディストダイアモンド」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 61,
      id: 159,
      name: '難題「火鼠の皮衣  -焦れぬ心-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 61,
      id: 160,
      name: '難題「火鼠の皮衣  -焦れぬ心-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 61,
      id: 161,
      name: '神宝「サラマンダーシールド」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 61,
      id: 162,
      name: '神宝「サラマンダーシールド」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 67,
      id: 163,
      name: '難題「燕の子安貝  -永命線-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 67,
      id: 164,
      name: '難題「燕の子安貝  -永命線-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 67,
      id: 165,
      name: '神宝「ライフスプリングインフィニティ」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 67,
      id: 166,
      name: '神宝「ライフスプリングインフィニティ」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 71,
      id: 167,
      name: '難題「蓬莱の弾の枝  -虹色の弾幕-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 71,
      id: 168,
      name: '難題「蓬莱の弾の枝  -虹色の弾幕-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 71,
      id: 169,
      name: '神宝「蓬莱の玉の枝  -夢色の郷-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 71,
      id: 170,
      name: '神宝「蓬莱の玉の枝  -夢色の郷-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 77,
      id: 171,
      name: '「永夜返し  -初月-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
    {
      sub: 77,
      id: 172,
      name: '「永夜返し  -三日月-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
    {
      sub: 77,
      id: 173,
      name: '「永夜返し  -上つ弓張-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
    {
      sub: 77,
      id: 174,
      name: '「永夜返し  -待宵-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
    {
      sub: 80,
      id: 175,
      name: '「永夜返し  -子の刻-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
    {
      sub: 80,
      id: 176,
      name: '「永夜返し  -子の二つ-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
    {
      sub: 80,
      id: 177,
      name: '「永夜返し  -子の三つ-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
    {
      sub: 80,
      id: 178,
      name: '「永夜返し  -子の四つ-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
    {
      sub: 82,
      id: 179,
      name: '「永夜返し  -丑の刻-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
    {
      sub: 82,
      id: 180,
      name: '「永夜返し  -丑の二つ-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
    {
      sub: 82,
      id: 181,
      name: '「永夜返し  -丑三つ時-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
    {
      sub: 82,
      id: 182,
      name: '「永夜返し  -丑の四つ-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
    {
      sub: 84,
      id: 183,
      name: '「永夜返し  -寅の刻-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
    {
      sub: 84,
      id: 184,
      name: '「永夜返し  -寅の二つ-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
    {
      sub: 84,
      id: 185,
      name: '「永夜返し  -寅の三つ-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
    {
      sub: 84,
      id: 186,
      name: '「永夜返し  -寅の四つ-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
    {
      sub: 87,
      id: 187,
      name: '「永夜返し  -朝靄-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
    {
      sub: 87,
      id: 188,
      name: '「永夜返し  -夜明け-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
    {
      sub: 87,
      id: 189,
      name: '「永夜返し  -明けの明星-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
    {
      sub: 87,
      id: 190,
      name: '「永夜返し  -世明け-」',
      owner: '蓬莱山輝夜',
      face: 0,
      bonus: 33000000,
      lastSpell: true,
    },
  ],
  scripts: SCRIPTS,
  waves: ECL_FILE,
};
