// Auto-generated facade for ecldata6.ecl by tools/th08/ecl.
// Do not edit directly; change the translator and run `npm run ecl:th08`.
//
// 88 subs, 1 timeline(s), 28 spell cards
// declared by op 122, 4 of them final spells per g_LastSpellNumbers.

import type { StageScript } from '../StageScript';
import * as SCRIPTS from './scripts';
import { ECL_FILE } from './waves';

export const STAGE6A_SCRIPT: StageScript = {
  route: 'stage6a',
  source: 'ecldata6.ecl',
  subCount: 88,
  timelineCount: 1,
  cards: [
    {
      sub: 21,
      id: 119,
      name: '天丸「壺中の天地」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 21,
      id: 120,
      name: '天丸「壺中の天地」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 21,
      id: 121,
      name: '天丸「壺中の天地」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 21,
      id: 122,
      name: '天丸「壺中の天地」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 52,
      id: 123,
      name: '覚神「神代の記憶」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 52,
      id: 124,
      name: '覚神「神代の記憶」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 52,
      id: 125,
      name: '神符「天人の系譜」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 52,
      id: 126,
      name: '神符「天人の系譜」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 56,
      id: 127,
      name: '蘇活「生命遊戯　-ライフゲーム-」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 56,
      id: 128,
      name: '蘇活「生命遊戯　-ライフゲーム-」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 56,
      id: 129,
      name: '蘇生「ライジングゲーム」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 56,
      id: 130,
      name: '蘇生「ライジングゲーム」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 63,
      id: 131,
      name: '操神「オモイカネディバイス」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 63,
      id: 132,
      name: '操神「オモイカネディバイス」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 63,
      id: 133,
      name: '神脳「オモイカネブレイン」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 63,
      id: 134,
      name: '神脳「オモイカネブレイン」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 68,
      id: 135,
      name: '天呪「アポロ１３」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 68,
      id: 136,
      name: '天呪「アポロ１３」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 68,
      id: 137,
      name: '天呪「アポロ１３」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 68,
      id: 138,
      name: '天呪「アポロ１３」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 73,
      id: 139,
      name: '秘術「天文密葬法」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 73,
      id: 140,
      name: '秘術「天文密葬法」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 73,
      id: 141,
      name: '秘術「天文密葬法」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 73,
      id: 142,
      name: '秘術「天文密葬法」',
      owner: '八意永琳',
      face: 0,
      bonus: 30000000,
      lastSpell: false,
    },
    {
      sub: 78,
      id: 143,
      name: '禁薬「蓬莱の薬」',
      owner: '八意永琳',
      face: 0,
      bonus: 5000000,
      lastSpell: true,
    },
    {
      sub: 78,
      id: 144,
      name: '禁薬「蓬莱の薬」',
      owner: '八意永琳',
      face: 0,
      bonus: 5000000,
      lastSpell: true,
    },
    {
      sub: 78,
      id: 145,
      name: '禁薬「蓬莱の薬」',
      owner: '八意永琳',
      face: 0,
      bonus: 5000000,
      lastSpell: true,
    },
    {
      sub: 78,
      id: 146,
      name: '禁薬「蓬莱の薬」',
      owner: '八意永琳',
      face: 0,
      bonus: 5000000,
      lastSpell: true,
    },
  ],
  scripts: SCRIPTS,
  waves: ECL_FILE,
};
