/**
 * Lift the retail effect template table into the game.
 *
 * `g_EffectTemplates[66]` lives in `th08.exe`'s `.data` at 0x4c6d30. The snapshot in
 * `effect-templates.ref.json` comes from the recompiled reference build
 * (`src/modern/linux/linux_runtime.cpp:148`, `InitializeTargetData`), and on 2026-09-16
 * it was checked against the shipped executable itself: `node .scratch/efftable.cjs`
 * maps the VA through the PE section table, reads all 66 rows (scriptIdx, the `field348`
 * update, the `callback` init) and every row agrees with this snapshot. The table is no
 * longer an inference from a rebuild. Each row carries the script index, the
 * per-frame update (`field348`) and the one-shot init (`callback`), and
 * the script index addresses `AnmManager::GetAnm(6)` -- `etama.anm` -- because
 * `EffectManager::AddedCallback` (`EffectManager.cpp:1347`) binds exactly the pack
 * `BulletManager` loaded there (`BulletManager.cpp:1609`). So the retail effects are
 * bullet art driven by bullet scripts, which is why this tool needs no new textures.
 *
 * Run: node tools/th08/anm/generate-effects.mjs
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '../../..');
const OUT = path.join(ROOT, 'src/games/th08/data/th08-effect-anm.ts');
const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'public/assets/th08/manifest.json'), 'utf8'));
const templates = JSON.parse(
  fs.readFileSync(path.join(ROOT, 'tools/th08/anm/effect-templates.ref.json'), 'utf8'),
);
if (templates.length !== 66) throw new Error(`expected 66 templates, got ${templates.length}`);
// Template 16 is `{0, 0, 0}`: script 0 with no movers. A snapshot that reads the script
// index as "absent" would put a hole in the table exactly where ECL can still point.
for (const [i, row] of templates.entries()) {
  if (!Number.isInteger(row.scriptIdx) || row.scriptIdx < 0) {
    throw new Error(`effect-templates.ref.json: template ${i} has no script index`);
  }
}

const scripts = manifest.anm.etama.scripts;
const behaviors = [...new Set(templates.flatMap((t) => [t.init, t.update]).filter(Boolean))].sort();

const lines = [
  '/**',
  ' * Generated by tools/th08/anm/generate-effects.mjs from effect-templates.ref.json and',
  ' * public/assets/th08/manifest.json (etama.anm). Do not edit by hand.',
  ' *',
  ' * The retail effect template table plus the untouched ANM bytecode of every script it',
  ' * can name. Effect ids in ECL (ops 128/139/140/174) are template ids, not script ids;',
  ' * `EFFECT_TEMPLATES[id]` is the translation between them.',
  ' */',
  '',
  '/**',
  ' * Decompile names for the two callbacks a template can carry.',
  ' *',
  ' * The update runs every frame before the script and retires the effect when it stops',
  ' * returning 1; the init runs once on the spawn frame and fails the spawn when it returns',
  ' * non-zero (`EffectManager.cpp:157-170`, `:1090-1105`).',
  ' */',
  'export type EffectBehavior =',
  behaviors.map((b, i) => `  | '${b}'${i === behaviors.length - 1 ? ';' : ''}`).join('\n'),
  '',
  '/** One row of `g_EffectTemplates`. */',
  'export interface EffectTemplate {',
  '  /** Script index inside `etama.anm` (`EffectManager.cpp:157`). */',
  '  readonly scriptIdx: number;',
  '  /** Per-frame mover, run before the ANM script. */',
  '  readonly update: EffectBehavior | null;',
  '  /** One-shot spawn setup, run after the script was attached. */',
  '  readonly init: EffectBehavior | null;',
  '}',
  '',
  '/** Effect id -> template, indexed exactly like the retail array. */',
  'export const EFFECT_TEMPLATES: readonly EffectTemplate[] = [',
  ...templates.map(
    (t) =>
      `  { scriptIdx: ${t.scriptIdx}, update: ${JSON.stringify(t.update)}, ` +
      `init: ${JSON.stringify(t.init)} },`,
  ),
  '];',
  '',
  '/**',
  ' * `etama.anm` script words, base64, indexed by retail script number.',
  ' *',
  ' * Every one of the 116 scripts is lifted: the templates already cover 56 of them and',
  ' * the bullet system may want the rest, while the whole pack is only kilobytes.',
  ' */',
  'export const TH08_EFFECT_SCRIPT_BYTES: readonly (string | null)[] = [',
  ...scripts.map((s) => `  '${s.base64}',`),
  '];',
  '',
  '/** Script words for one template id, or null when the pack is not loaded. */',
  'export function effectScriptBytes(id: number): string | null {',
  '  const template = EFFECT_TEMPLATES[id];',
  '  if (!template) return null;',
  '  return TH08_EFFECT_SCRIPT_BYTES[template.scriptIdx] ?? null;',
  '}',
  '',
];
fs.writeFileSync(OUT, lines.join('\n'));
console.log(
  `${path.relative(ROOT, OUT)}: ${templates.length} templates, ${behaviors.length} behaviors, ` +
    `${scripts.length} scripts, ${Math.round(fs.statSync(OUT).size / 1024)} KB`,
);
