// Auto-generated facade for ecldata5.ecl by tools/th08/ecl.
// Do not edit directly; change the translator and run `npm run ecl:th08`.
//
// 90 subs, 1 timeline(s), 19 spell cards
// declared by op 122, 3 of them final spells per g_LastSpellNumbers.

import type { StageScript } from '../StageScript';
import * as SCRIPTS from './scripts';
import { ECL_FILE } from './waves';

export const STAGE5_SCRIPT: StageScript = {
  route: 'stage5',
  source: 'ecldata5.ecl',
  subCount: 90,
  timelineCount: 1,
  cards: [
    {
      sub: 62,
      id: 100,
      name: '波符「赤眼催眠(マインドシェイカー)」',
      owner: '鈴仙・Ｕ・イナバ',
      face: 0,
      bonus: 26000000,
      lastSpell: false,
    },
    {
      sub: 62,
      id: 101,
      name: '波符「赤眼催眠(マインドシェイカー)」',
      owner: '鈴仙・Ｕ・イナバ',
      face: 0,
      bonus: 26000000,
      lastSpell: false,
    },
    {
      sub: 62,
      id: 102,
      name: '幻波「赤眼催眠(マインドブローイング)」',
      owner: '鈴仙・Ｕ・イナバ',
      face: 0,
      bonus: 26000000,
      lastSpell: false,
    },
    {
      sub: 62,
      id: 103,
      name: '幻波「赤眼催眠(マインドブローイング)」',
      owner: '鈴仙・Ｕ・イナバ',
      face: 0,
      bonus: 26000000,
      lastSpell: false,
    },
    {
      sub: 63,
      id: 108,
      name: '懶符「生神停止(アイドリングウェーブ」',
      owner: '鈴仙・Ｕ・イナバ',
      face: 0,
      bonus: 26000000,
      lastSpell: false,
    },
    {
      sub: 63,
      id: 109,
      name: '懶符「生神停止(アイドリングウェーブ)」',
      owner: '鈴仙・Ｕ・イナバ',
      face: 0,
      bonus: 26000000,
      lastSpell: false,
    },
    {
      sub: 63,
      id: 110,
      name: '懶惰「生神停止(マインドストッパー)」',
      owner: '鈴仙・Ｕ・イナバ',
      face: 0,
      bonus: 26000000,
      lastSpell: false,
    },
    {
      sub: 63,
      id: 111,
      name: '懶惰「生神停止(マインドストッパー)」',
      owner: '鈴仙・Ｕ・イナバ',
      face: 0,
      bonus: 26000000,
      lastSpell: false,
    },
    {
      sub: 66,
      id: 104,
      name: '狂符「幻視調律(ビジョナリチューニング)」',
      owner: '鈴仙・Ｕ・イナバ',
      face: 0,
      bonus: 26000000,
      lastSpell: false,
    },
    {
      sub: 66,
      id: 105,
      name: '狂符「幻視調律(ビジョナリチューニング)」',
      owner: '鈴仙・Ｕ・イナバ',
      face: 0,
      bonus: 26000000,
      lastSpell: false,
    },
    {
      sub: 66,
      id: 106,
      name: '狂視「狂視調律(イリュージョンシーカー)」',
      owner: '鈴仙・Ｕ・イナバ',
      face: 0,
      bonus: 26000000,
      lastSpell: false,
    },
    {
      sub: 66,
      id: 107,
      name: '狂視「狂視調律(イリュージョンシーカー)」',
      owner: '鈴仙・Ｕ・イナバ',
      face: 0,
      bonus: 26000000,
      lastSpell: false,
    },
    {
      sub: 75,
      id: 112,
      name: '散符「真実の月(インビジブルフルムーン)」',
      owner: '鈴仙・Ｕ・イナバ',
      face: 0,
      bonus: 26000000,
      lastSpell: false,
    },
    {
      sub: 75,
      id: 113,
      name: '散符「真実の月(インビジブルフルムーン)」',
      owner: '鈴仙・Ｕ・イナバ',
      face: 0,
      bonus: 26000000,
      lastSpell: false,
    },
    {
      sub: 75,
      id: 114,
      name: '散符「真実の月(インビジブルフルムーン)」',
      owner: '鈴仙・Ｕ・イナバ',
      face: 0,
      bonus: 26000000,
      lastSpell: false,
    },
    {
      sub: 75,
      id: 115,
      name: '散符「真実の月(インビジブルフルムーン)」',
      owner: '鈴仙・Ｕ・イナバ',
      face: 0,
      bonus: 26000000,
      lastSpell: false,
    },
    {
      sub: 78,
      id: 116,
      name: '月眼「月兎遠隔催眠術(テレメスメリズム)」',
      owner: '鈴仙・Ｕ・イナバ',
      face: 0,
      bonus: 30000000,
      lastSpell: true,
    },
    {
      sub: 78,
      id: 117,
      name: '月眼「月兎遠隔催眠術(テレメスメリズム)」',
      owner: '鈴仙・Ｕ・イナバ',
      face: 0,
      bonus: 30000000,
      lastSpell: true,
    },
    {
      sub: 78,
      id: 118,
      name: '月眼「月兎遠隔催眠術(テレメスメリズム)」',
      owner: '鈴仙・Ｕ・イナバ',
      face: 0,
      bonus: 30000000,
      lastSpell: true,
    },
  ],
  scripts: SCRIPTS,
  waves: ECL_FILE,
};
