// Auto-generated facade for ecldata3.ecl by tools/th08/ecl.
// Do not edit directly; change the translator and run `npm run ecl:th08`.
//
// 78 subs, 4 timeline(s), 22 spell cards
// declared by op 122, 3 of them final spells per g_LastSpellNumbers.

import type { StageScript } from '../StageScript';
import * as SCRIPTS from './scripts';
import { ECL_FILE } from './waves';

export const STAGE3_SCRIPT: StageScript = {
  route: 'stage3',
  source: 'ecldata3.ecl',
  subCount: 78,
  timelineCount: 4,
  cards: [
    {
      sub: 30,
      id: 32,
      name: '産霊「ファーストピラミッド」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: false,
    },
    {
      sub: 30,
      id: 33,
      name: '産霊「ファーストピラミッド」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: false,
    },
    {
      sub: 30,
      id: 34,
      name: '産霊「ファーストピラミッド」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: false,
    },
    {
      sub: 30,
      id: 35,
      name: '産霊「ファーストピラミッド」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: false,
    },
    {
      sub: 44,
      id: 36,
      name: '始符「エフェメラリティ137」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: false,
    },
    {
      sub: 44,
      id: 37,
      name: '始符「エフェメラリティ137」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: false,
    },
    {
      sub: 44,
      id: 38,
      name: '始符「エフェメラリティ137」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: false,
    },
    {
      sub: 47,
      id: 39,
      name: '野符「武烈クライシス」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: false,
    },
    {
      sub: 47,
      id: 40,
      name: '野符「将門クライシス」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: false,
    },
    {
      sub: 47,
      id: 41,
      name: '野符「義満クライシス」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: false,
    },
    {
      sub: 47,
      id: 42,
      name: '野符「GHQクライシス」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: false,
    },
    {
      sub: 50,
      id: 43,
      name: '国符「三種の神器　剣」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: false,
    },
    {
      sub: 54,
      id: 44,
      name: '国符「三種の神器　玉」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: false,
    },
    {
      sub: 58,
      id: 45,
      name: '国符「三種の神器　鏡」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: false,
    },
    {
      sub: 62,
      id: 46,
      name: '国体「三種の神器　郷」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: false,
    },
    {
      sub: 67,
      id: 47,
      name: '終符「幻想天皇」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: false,
    },
    {
      sub: 67,
      id: 48,
      name: '終符「幻想天皇」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: false,
    },
    {
      sub: 67,
      id: 49,
      name: '虚史「幻想郷伝説」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: false,
    },
    {
      sub: 67,
      id: 50,
      name: '虚史「幻想郷伝説」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: false,
    },
    {
      sub: 71,
      id: 51,
      name: '未来「高天原」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: true,
    },
    {
      sub: 71,
      id: 52,
      name: '未来「高天原」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: true,
    },
    {
      sub: 71,
      id: 53,
      name: '未来「高天原」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 20000000,
      lastSpell: true,
    },
  ],
  scripts: SCRIPTS,
  waves: ECL_FILE,
};
