export type StageNumber = 1 | 2 | 3 | 4 | 5 | 6;
export type Difficulty = 'easy' | 'normal' | 'hard' | 'lunatic';
import {
  CHARACTER_PROFILES,
  type CharacterId,
  type CharacterProfile,
} from '../../touhou-common/player/CharacterProfile';
export { CHARACTER_PROFILES };
export type { CharacterId, CharacterProfile } from '../../touhou-common/player/CharacterProfile';

export const DIFFICULTY_MODIFIERS: Record<
  Difficulty,
  {
    label: string;
    bulletSpeed: number;
    bulletDensity: number;
    enemyHp: number;
    /**
     * Boss life-bar multiplier. Deliberately gentler than `enemyHp`: a boss already
     * gains an extra life on Hard/Lunatic, and stacking both would turn the last
     * cards into a minute-long grind.
     */
    bossHp: number;
  }
> = {
  easy: { label: 'Easy', bulletSpeed: 0.82, bulletDensity: 0.72, enemyHp: 0.8, bossHp: 0.75 },
  normal: { label: 'Normal', bulletSpeed: 1, bulletDensity: 1, enemyHp: 1, bossHp: 1 },
  hard: { label: 'Hard', bulletSpeed: 1.12, bulletDensity: 1.18, enemyHp: 1.2, bossHp: 1.1 },
  lunatic: { label: 'Lunatic', bulletSpeed: 1.25, bulletDensity: 1.4, enemyHp: 1.45, bossHp: 1.2 },
};

export interface StageMetadata {
  stage: StageNumber;
  title: string;
  boss: string;
  theme: string;
  /** Parallax art set for the stage (see tools/art/backgrounds.mjs). */
  bgTheme: StageTheme;
  cycleFrames: number;
  /**
   * Ambient light on the painted backdrop. Every TH08 stage keeps one fixed
   * level for its whole length — the mood of the hour, not a day/night cycle.
   */
  bgBrightness: number;
  /** How fast the backdrop scrolls down, in playfield pixels per frame. */
  bgScroll: number;
}

export const STAGE_METADATA: Record<StageNumber, StageMetadata> = {
  1: {
    stage: 1,
    title: '暗闇の夜',
    boss: 'ルミア',
    theme: 'The Missing Night',
    cycleFrames: 3600,
    bgTheme: 'forestNight',
    bgBrightness: 0.55,
    bgScroll: 1.1,
  },
  2: {
    stage: 2,
    title: '蠢々秋月',
    boss: 'リグル・ナイトバグ',
    theme: 'Mooned Insect',
    cycleFrames: 3300,
    bgTheme: 'lake',
    bgBrightness: 0.6,
    bgScroll: 1,
  },
  3: {
    stage: 3,
    title: '夜雀の歌声',
    boss: 'ミスティア・ローレライ',
    theme: 'Night Bird',
    cycleFrames: 3900,
    bgTheme: 'nightSky',
    bgBrightness: 0.5,
    bgScroll: 1.25,
  },
  4: {
    stage: 4,
    title: '懐かしき東方の血',
    boss: '上白沢慧音',
    theme: 'Old World',
    cycleFrames: 3600,
    bgTheme: 'bambooMoon',
    bgBrightness: 0.62,
    bgScroll: 1.35,
  },
  5: {
    stage: 5,
    title: '永夜返し',
    boss: '鈴仙・優曇華院・イナバ',
    theme: 'Eternally Dusk',
    cycleFrames: 4200,
    bgTheme: 'village',
    bgBrightness: 0.58,
    bgScroll: 1.2,
  },
  6: {
    stage: 6,
    title: '千年幻想郷',
    boss: '八意永琳',
    theme: 'History of the Moon',
    cycleFrames: 4500,
    bgTheme: 'moonCity',
    bgBrightness: 0.72,
    bgScroll: 0.9,
  },
};

/** Baked texture atlas: 213 PNGs generated by tools/generate-assets.mjs. */
export { ASSET_MANIFEST, BULLET_PALETTE, BULLET_SHAPE_KEYS, ASSET_KEYS } from './data/asset-manifest';
export type { AssetManifest } from '../../engine/renderer/AssetManager';

/** Background themes available in the atlas. */
export type StageTheme = 'forestNight' | 'lake' | 'nightSky' | 'village' | 'bambooMoon' | 'moonCity';

export const STAGE_THEMES: StageTheme[] = [
  'forestNight',
  'lake',
  'nightSky',
  'village',
  'bambooMoon',
  'moonCity',
];

export function isStageNumber(value: number): value is StageNumber {
  return Number.isInteger(value) && value >= 1 && value <= 6;
}

export function getCharacterProfile(id: CharacterId = 'reimu-yukari'): CharacterProfile {
  return { ...CHARACTER_PROFILES[id] };
}
