import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

/**
 * Reproducible webp -> png baking for the vendored Taisei atlas.
 *
 * Taisei ships most of its art as lossless webp, which browsers decode happily.
 * Two cases need real work before they can be used:
 *
 *  1. `X.webp` + `X.alphamap.webp` pairs (the focus circles and a few portraits).
 *     The colour file is fully opaque and the alpha lives in a second image, so
 *     loading the colour file alone turns a delicate ring into a solid grey ball.
 *     ffmpeg merges each pair into one RGBA png under `baked/`.
 *  2. `proj/*.webp` bullet masks, which tools/art/taisei-bullets.mjs reads back
 *     channel by channel through our PNG-only decoder. Those become `mask/*.png`.
 *
 * Both steps need ffmpeg (override the binary with TAISEI_FFMPEG). Without it the
 * generator keeps pointing at the raw webp and reports what it could not bake.
 */

/** TAISEI_FFMPEG wins, then `ffmpeg` on PATH. */
function ffmpegCommand() {
  const fromEnv = process.env.TAISEI_FFMPEG;
  const bin = fromEnv && existsSync(fromEnv) ? fromEnv : 'ffmpeg';
  return spawnSync(bin, ['-version']).status === 0 ? bin : null;
}

function walk(dir, base = dir, out = []) {
  if (!existsSync(dir)) return out;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) walk(full, base, out);
    else out.push(full.slice(base.length + 1).split(/[\\/]/).join('/'));
  }
  return out;
}

/** True when `out` exists and is at least as new as `src`. */
function upToDate(out, src) {
  return existsSync(out) && statSync(out).mtimeMs >= statSync(src).mtimeMs;
}

function run(bin, args) {
  return spawnSync(bin, args, { stdio: 'ignore' }).status === 0;
}

/**
 * @param {string} root project root
 * @returns {{ bin: string|null, baked: string[], masks: string[], failures: string[] }}
 */
export function bakeTaiseiWebp(root) {
  const dir = join(root, 'public', 'assets', 'taisei');
  const result = { bin: null, baked: [], masks: [], failures: [] };
  const bin = ffmpegCommand();
  if (!bin) return result;
  result.bin = bin;

  const rels = walk(dir);
  const maps = rels.filter((r) => r.endsWith('.alphamap.webp'));

  // 1. Colour + alphamap pairs -> baked/<rel>.png
  for (const rel of maps) {
    const colour = rel.replace(/\.alphamap\.webp$/, '.webp');
    if (!rels.includes(colour)) continue;
    const relOut = 'baked/' + colour.replace(/\.webp$/, '.png');
    const out = join(dir, relOut);
    if (upToDate(out, join(dir, colour)) && upToDate(out, join(dir, rel))) {
      result.baked.push(relOut);
      continue;
    }
    mkdirSync(dirname(out), { recursive: true });
    const args = [
      '-y', '-loglevel', 'error',
      '-i', join(dir, colour),
      '-i', join(dir, rel),
      '-filter_complex', '[0:v][1:v]alphamerge',
      out,
    ];
    if (run(bin, args)) result.baked.push(relOut);
    else result.failures.push(colour);
  }

  // 2. Bullet masks for tools/art/taisei-bullets.mjs
  for (const rel of rels) {
    if (!rel.startsWith('proj/') || !rel.endsWith('.webp')) continue;
    const relOut = 'mask/' + rel.slice('proj/'.length).replace(/\.webp$/, '.png');
    const out = join(dir, relOut);
    if (upToDate(out, join(dir, rel))) {
      result.masks.push(relOut);
      continue;
    }
    mkdirSync(dirname(out), { recursive: true });
    if (run(bin, ['-y', '-loglevel', 'error', '-i', join(dir, rel), out])) result.masks.push(relOut);
    else result.failures.push(rel);
  }

  if (result.baked.length) {
    writeFileSync(
      join(dir, 'baked', 'README.txt'),
      'Generated by tools/art/taisei-bake.mjs from the vendored Taisei webp atlas.\n' +
        '\n' +
        'baked/<name>.png merges <name>.webp with <name>.alphamap.webp: Taisei stores\n' +
        'the alpha of these sprites in a separate file, so the raw webp is opaque and\n' +
        'renders as a solid blob. Art without an alphamap stays as webp.\n',
    );
  }
  return result;
}