// Auto-generated facade for ecldata4b.ecl by tools/th08/ecl.
// Do not edit directly; change the translator and run `npm run ecl:th08`.
//
// 78 subs, 2 timeline(s), 23 spell cards
// declared by op 122, 3 of them final spells per g_LastSpellNumbers.

import type { StageScript } from '../StageScript';
import * as SCRIPTS from './scripts';
import { ECL_FILE } from './waves';

export const STAGE4B_SCRIPT: StageScript = {
  route: 'stage4b',
  source: 'ecldata4b.ecl',
  subCount: 78,
  timelineCount: 2,
  cards: [
    {
      sub: 36,
      id: 77,
      name: '魔符「ミルキーウェイ」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 36,
      id: 78,
      name: '魔符「ミルキーウェイ」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 36,
      id: 79,
      name: '魔空「アステロイドベルト」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 36,
      id: 80,
      name: '魔空「アステロイドベルト」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 41,
      id: 81,
      name: '魔符「スターダストレヴァリエ」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 41,
      id: 82,
      name: '魔符「スターダストレヴァリエ」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 41,
      id: 83,
      name: '黒魔「イベントホライズン」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 41,
      id: 84,
      name: '黒魔「イベントホライズン」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 47,
      id: 85,
      name: '恋符「ノンディレクショナルレーザー」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 47,
      id: 86,
      name: '恋符「ノンディレクショナルレーザー」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 47,
      id: 87,
      name: '恋風「スターライトタイフーン」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 47,
      id: 88,
      name: '恋風「スターライトタイフーン」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 55,
      id: 89,
      name: '恋符「マスタースパーク」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 55,
      id: 90,
      name: '恋符「マスタースパーク」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 55,
      id: 91,
      name: '恋心「ダブルスパーク」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 55,
      id: 92,
      name: '恋心「ダブルスパーク」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 62,
      id: 93,
      name: '光符「アースライトレイ」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 25000000,
      lastSpell: false,
    },
    {
      sub: 62,
      id: 94,
      name: '光符「アースライトレイ」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 25000000,
      lastSpell: false,
    },
    {
      sub: 62,
      id: 95,
      name: '光撃「シュート・ザ・ムーン」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 25000000,
      lastSpell: false,
    },
    {
      sub: 62,
      id: 96,
      name: '光撃「シュート・ザ・ムーン」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 25000000,
      lastSpell: false,
    },
    {
      sub: 67,
      id: 97,
      name: '魔砲「ファイナルスパーク」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 25000000,
      lastSpell: true,
    },
    {
      sub: 67,
      id: 98,
      name: '魔砲「ファイナルスパーク」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 25000000,
      lastSpell: true,
    },
    {
      sub: 67,
      id: 99,
      name: '魔砲「ファイナルマスタースパーク」',
      owner: '霧雨魔理沙',
      face: 0,
      bonus: 25000000,
      lastSpell: true,
    },
  ],
  scripts: SCRIPTS,
  waves: ECL_FILE,
};
