/**
 * HUD art rects from the original `front.anm` and `ascii.anm` sheets.
 * Auto-generated by `tools/gen-hud.mjs` from public/assets/th08/manifest.json.
 *
 * `front` entry 0 is the panel: id 0 is the 永夜抄 logo plate, ids 2-9 the row
 * labels in retail order (HiScore, Score, Player, Spell, Power, Graze, Point,
 * Time), ids 11/12 the life/bomb stars, id 13 the 32x32 backdrop tile.
 *
 * `ascii` carries the 16x16 game font contiguously from id 31, which is U+0020.
 * `AsciiManager.cpp:483` indexes it as `char + (31 - ' ')`, so glyph id is
 * `charCode - 1` and the advance is `spaceWidth` = 13, not the 16 of the cell.
 * Ids 152-156 are the 妖率計: 155 is the whole ornate track, 153/154 the 人/妖
 * limit icons.
 *
 * The badges live on `ascii` entry 2 (`ascii_t2.png`), not the font page.
 */

export interface HudRect {
  x: number;
  y: number;
  w: number;
  h: number;
}

export const TH08_FRONT_ATLAS = '/assets/th08/anm/front_t0.png';
export const TH08_ASCII_ATLAS = '/assets/th08/anm/ascii_t0.png';
export const TH08_ASCII2_ATLAS = '/assets/th08/anm/ascii_t2.png';

/** First code point the 16x16 font covers (a space). */
export const ASCII_FIRST_GLYPH = 0x20;
/** Number of code points in the contiguous run, i.e. 0x20..0x7F. */
export const ASCII_GLYPH_COUNT = 96;
export const asciiGlyphId = (code: number): number => code - 1;

export const TH08_FRONT_RECTS: Record<number, HudRect> = {
  0: { x: 128, y: 0, w: 128, h: 256 },
  1: { x: 0, y: 1, w: 128, h: 31 },
  2: { x: 0, y: 80, w: 64, h: 16 },
  3: { x: 0, y: 96, w: 64, h: 16 },
  4: { x: 0, y: 112, w: 64, h: 16 },
  5: { x: 0, y: 128, w: 64, h: 16 },
  6: { x: 0, y: 144, w: 64, h: 16 },
  7: { x: 0, y: 160, w: 64, h: 16 },
  8: { x: 0, y: 176, w: 64, h: 16 },
  9: { x: 0, y: 192, w: 64, h: 16 },
  10: { x: 0, y: 208, w: 128, h: 16 },
  11: { x: 64, y: 80, w: 16, h: 16 },
  12: { x: 80, y: 80, w: 16, h: 16 },
  13: { x: 0, y: 224, w: 32, h: 32 },
  14: { x: 0, y: 240, w: 128, h: 16 },
  15: { x: 0, y: 240, w: 160, h: 16 },
};

export const TH08_ASCII_RECTS: Record<number, HudRect> = {
  31: { x: 0, y: 32, w: 16, h: 16 },
  32: { x: 16, y: 32, w: 16, h: 16 },
  33: { x: 32, y: 32, w: 16, h: 16 },
  34: { x: 48, y: 32, w: 16, h: 16 },
  35: { x: 64, y: 32, w: 16, h: 16 },
  36: { x: 80, y: 32, w: 16, h: 16 },
  37: { x: 96, y: 32, w: 16, h: 16 },
  38: { x: 112, y: 32, w: 16, h: 16 },
  39: { x: 128, y: 32, w: 16, h: 16 },
  40: { x: 144, y: 32, w: 16, h: 16 },
  41: { x: 160, y: 32, w: 16, h: 16 },
  42: { x: 176, y: 32, w: 16, h: 16 },
  43: { x: 192, y: 32, w: 16, h: 16 },
  44: { x: 208, y: 32, w: 16, h: 16 },
  45: { x: 224, y: 32, w: 16, h: 16 },
  46: { x: 240, y: 32, w: 16, h: 16 },
  47: { x: 0, y: 48, w: 16, h: 16 },
  48: { x: 16, y: 48, w: 16, h: 16 },
  49: { x: 32, y: 48, w: 16, h: 16 },
  50: { x: 48, y: 48, w: 16, h: 16 },
  51: { x: 64, y: 48, w: 16, h: 16 },
  52: { x: 80, y: 48, w: 16, h: 16 },
  53: { x: 96, y: 48, w: 16, h: 16 },
  54: { x: 112, y: 48, w: 16, h: 16 },
  55: { x: 128, y: 48, w: 16, h: 16 },
  56: { x: 144, y: 48, w: 16, h: 16 },
  57: { x: 160, y: 48, w: 16, h: 16 },
  58: { x: 176, y: 48, w: 16, h: 16 },
  59: { x: 192, y: 48, w: 16, h: 16 },
  60: { x: 208, y: 48, w: 16, h: 16 },
  61: { x: 224, y: 48, w: 16, h: 16 },
  62: { x: 240, y: 48, w: 16, h: 16 },
  63: { x: 0, y: 64, w: 16, h: 16 },
  64: { x: 16, y: 64, w: 16, h: 16 },
  65: { x: 32, y: 64, w: 16, h: 16 },
  66: { x: 48, y: 64, w: 16, h: 16 },
  67: { x: 64, y: 64, w: 16, h: 16 },
  68: { x: 80, y: 64, w: 16, h: 16 },
  69: { x: 96, y: 64, w: 16, h: 16 },
  70: { x: 112, y: 64, w: 16, h: 16 },
  71: { x: 128, y: 64, w: 16, h: 16 },
  72: { x: 144, y: 64, w: 16, h: 16 },
  73: { x: 160, y: 64, w: 16, h: 16 },
  74: { x: 176, y: 64, w: 16, h: 16 },
  75: { x: 192, y: 64, w: 16, h: 16 },
  76: { x: 208, y: 64, w: 16, h: 16 },
  77: { x: 224, y: 64, w: 16, h: 16 },
  78: { x: 240, y: 64, w: 16, h: 16 },
  79: { x: 0, y: 80, w: 16, h: 16 },
  80: { x: 16, y: 80, w: 16, h: 16 },
  81: { x: 32, y: 80, w: 16, h: 16 },
  82: { x: 48, y: 80, w: 16, h: 16 },
  83: { x: 64, y: 80, w: 16, h: 16 },
  84: { x: 80, y: 80, w: 16, h: 16 },
  85: { x: 96, y: 80, w: 16, h: 16 },
  86: { x: 112, y: 80, w: 16, h: 16 },
  87: { x: 128, y: 80, w: 16, h: 16 },
  88: { x: 144, y: 80, w: 16, h: 16 },
  89: { x: 160, y: 80, w: 16, h: 16 },
  90: { x: 176, y: 80, w: 16, h: 16 },
  91: { x: 192, y: 80, w: 16, h: 16 },
  92: { x: 208, y: 80, w: 16, h: 16 },
  93: { x: 224, y: 80, w: 16, h: 16 },
  94: { x: 240, y: 80, w: 16, h: 16 },
  95: { x: 0, y: 96, w: 16, h: 16 },
  96: { x: 16, y: 96, w: 16, h: 16 },
  97: { x: 32, y: 96, w: 16, h: 16 },
  98: { x: 48, y: 96, w: 16, h: 16 },
  99: { x: 64, y: 96, w: 16, h: 16 },
  100: { x: 80, y: 96, w: 16, h: 16 },
  101: { x: 96, y: 96, w: 16, h: 16 },
  102: { x: 112, y: 96, w: 16, h: 16 },
  103: { x: 128, y: 96, w: 16, h: 16 },
  104: { x: 144, y: 96, w: 16, h: 16 },
  105: { x: 160, y: 96, w: 16, h: 16 },
  106: { x: 176, y: 96, w: 16, h: 16 },
  107: { x: 192, y: 96, w: 16, h: 16 },
  108: { x: 208, y: 96, w: 16, h: 16 },
  109: { x: 224, y: 96, w: 16, h: 16 },
  110: { x: 240, y: 96, w: 16, h: 16 },
  111: { x: 0, y: 112, w: 16, h: 16 },
  112: { x: 16, y: 112, w: 16, h: 16 },
  113: { x: 32, y: 112, w: 16, h: 16 },
  114: { x: 48, y: 112, w: 16, h: 16 },
  115: { x: 64, y: 112, w: 16, h: 16 },
  116: { x: 80, y: 112, w: 16, h: 16 },
  117: { x: 96, y: 112, w: 16, h: 16 },
  118: { x: 112, y: 112, w: 16, h: 16 },
  119: { x: 128, y: 112, w: 16, h: 16 },
  120: { x: 144, y: 112, w: 16, h: 16 },
  121: { x: 160, y: 112, w: 16, h: 16 },
  122: { x: 176, y: 112, w: 16, h: 16 },
  123: { x: 192, y: 112, w: 16, h: 16 },
  124: { x: 208, y: 112, w: 16, h: 16 },
  125: { x: 224, y: 112, w: 16, h: 16 },
  126: { x: 240, y: 112, w: 16, h: 16 },
};

/** 妖率計 pieces, by `ascii.anm` sprite id. */
export const TH08_GAUGE_RECTS: Record<number, HudRect> = {
  152: { x: 128, y: 208, w: 8, h: 12 },
  153: { x: 160, y: 208, w: 16, h: 16 },
  154: { x: 176, y: 208, w: 16, h: 16 },
  155: { x: 0, y: 224, w: 128, h: 16 },
  156: { x: 128, y: 224, w: 48, h: 16 },
};

/** Difficulty / 符卡 badges, by `ascii.anm` sprite id (entry 2). */
export const TH08_BADGE_RECTS: Record<number, HudRect> = {
  282: { x: 0, y: 224, w: 160, h: 32 },
  283: { x: 192, y: 0, w: 64, h: 16 },
  284: { x: 192, y: 16, w: 64, h: 16 },
  285: { x: 128, y: 0, w: 64, h: 16 },
  286: { x: 128, y: 16, w: 64, h: 16 },
  287: { x: 192, y: 192, w: 64, h: 16 },
  288: { x: 192, y: 208, w: 64, h: 16 },
};

/** Score-popup glyphs, by `ascii.anm` sprite id (three 11-cell banks). */
export const TH08_POPUP_RECTS: Record<number, HudRect> = {
  0: { x: 0, y: 0, w: 8, h: 8 },
  1: { x: 8, y: 0, w: 8, h: 8 },
  2: { x: 16, y: 0, w: 8, h: 8 },
  3: { x: 24, y: 0, w: 8, h: 8 },
  4: { x: 32, y: 0, w: 8, h: 8 },
  5: { x: 40, y: 0, w: 8, h: 8 },
  6: { x: 48, y: 0, w: 8, h: 8 },
  7: { x: 56, y: 0, w: 8, h: 8 },
  8: { x: 64, y: 0, w: 8, h: 8 },
  9: { x: 72, y: 0, w: 8, h: 8 },
  10: { x: 80, y: 0, w: 48, h: 8 },
  11: { x: 128, y: 0, w: 8, h: 8 },
  12: { x: 136, y: 0, w: 8, h: 8 },
  13: { x: 144, y: 0, w: 8, h: 8 },
  14: { x: 152, y: 0, w: 8, h: 8 },
  15: { x: 160, y: 0, w: 8, h: 8 },
  16: { x: 168, y: 0, w: 8, h: 8 },
  17: { x: 176, y: 0, w: 8, h: 8 },
  18: { x: 184, y: 0, w: 8, h: 8 },
  19: { x: 192, y: 0, w: 8, h: 8 },
  20: { x: 200, y: 0, w: 8, h: 8 },
  21: { x: 128, y: 8, w: 8, h: 8 },
  22: { x: 136, y: 8, w: 8, h: 8 },
  23: { x: 144, y: 8, w: 8, h: 8 },
  24: { x: 152, y: 8, w: 8, h: 8 },
  25: { x: 160, y: 8, w: 8, h: 8 },
  26: { x: 168, y: 8, w: 8, h: 8 },
  27: { x: 176, y: 8, w: 8, h: 8 },
  28: { x: 184, y: 8, w: 8, h: 8 },
  29: { x: 192, y: 8, w: 8, h: 8 },
  30: { x: 200, y: 8, w: 8, h: 8 },
};
