/**
 * Register the cells the *ship's own* animation packs carry.
 *
 * `g_PlayerAnmFilenames` (`Player.cpp:44-47`) points every shot type at one of the
 * four `playerNN.anm` packs, and the same pack holds the shot sprites, the 式神 and
 * blade bodies, and the hit sparks - `FUN_0044fb70` runs a shot's script out of
 * `g_PlayerAnm`, not out of `etama.anm`. Those cells were never sliced, which is why
 * the ship's weapon has been drawing with invented art while the enemy bullets had
 * the real thing.
 *
 * The rectangles are retail's own, generated by `tools/th08/anm/generate-player.mjs`
 * from the manifest the extractor wrote, so nothing here is measured by eye.
 */
import type { PixiRenderer } from '../../../engine/renderer/PixiRenderer';
import { TH08_PLAYER_ANM_PACKS } from '../../../th08/data/th08-player-anm';
import { sliceAtlas } from './th08-player-registration';

/** The asset base the extractor's page PNGs are served from. */
const ANM_BASE = '/assets/th08/anm/';

/** One drawn cell: `th08:pshot:player01_t0:14` and friends. */
export function th08PlayerCellKey(team: number, page: number, sprite: number): string {
  return `th08:pshot:player${String(team).padStart(2, '0')}_t${page}:${sprite}`;
}

/** The pack a shot type draws from, i.e. `g_PlayerAnmFilenames[shotType]`. */
export function th08PlayerAnmTeam(shotType: number): number {
  const table = [0, 1, 2, 3, 0, 0, 1, 1, 2, 2, 3, 3];
  return table[Math.max(0, Math.min(11, shotType | 0))];
}

/**
 * Slice and register every cell of the four packs. Returns how many cells landed;
 * a zero means the extracted pages are not in place, which is when the fallback
 * bullet art has to keep working.
 */
export async function registerTH08PlayerCells(renderer: PixiRenderer): Promise<number> {
  let count = 0;
  for (let team = 0; team < TH08_PLAYER_ANM_PACKS.length; team++) {
    const data = TH08_PLAYER_ANM_PACKS[team];
    if (!data) continue;
    for (let page = 0; page < data.pages.length; page++) {
      const frames = data.rects
        .map((rect, sprite) => ({ rect, sprite }))
        .filter((entry) => entry.rect !== null && entry.rect.tex === page)
        .map((entry) => ({
          id: entry.sprite,
          x: entry.rect!.x,
          y: entry.rect!.y,
          w: entry.rect!.w,
          h: entry.rect!.h,
        }));
      if (frames.length === 0) continue;
      try {
        const textures = await sliceAtlas(ANM_BASE + data.pages[page], frames);
        for (const frame of frames) {
          const texture = textures.get(frame.id);
          if (!texture) continue;
          renderer.assets.register(th08PlayerCellKey(team, page, frame.id), texture);
          count++;
        }
      } catch {
        // Pages not extracted: the invented-art fallback stays in charge.
      }
    }
  }
  return count;
}

/** The cell box a sprite id occupies in a pack, for a host that sizes its own quad. */
export function th08PlayerCellSize(
  team: number,
  sprite: number,
): { w: number; h: number } | null {
  const rect = TH08_PLAYER_ANM_PACKS[team]?.rects[sprite];
  return rect ? { w: rect.w, h: rect.h } : null;
}
