// Auto-generated facade for ecldata2.ecl by tools/th08/ecl.
// Do not edit directly; change the translator and run `npm run ecl:th08`.
//
// 65 subs, 2 timeline(s), 21 spell cards
// declared by op 122, 3 of them final spells per g_LastSpellNumbers.

import type { StageScript } from '../StageScript';
import * as SCRIPTS from './scripts';
import { ECL_FILE } from './waves';

export const STAGE2_SCRIPT: StageScript = {
  route: 'stage2',
  source: 'ecldata2.ecl',
  subCount: 65,
  timelineCount: 2,
  cards: [
    {
      sub: 23,
      id: 13,
      name: '声符「梟の夜鳴声」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: false,
    },
    {
      sub: 23,
      id: 14,
      name: '声符「梟の夜鳴声」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: false,
    },
    {
      sub: 23,
      id: 15,
      name: '声符「木菟咆哮」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: false,
    },
    {
      sub: 23,
      id: 16,
      name: '声符「木菟咆哮」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: false,
    },
    {
      sub: 33,
      id: 17,
      name: '蛾符「天蛾の蠱道」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: false,
    },
    {
      sub: 33,
      id: 18,
      name: '蛾符「天蛾の蠱道」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: false,
    },
    {
      sub: 33,
      id: 19,
      name: '毒符「毒蛾の鱗粉」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: false,
    },
    {
      sub: 33,
      id: 20,
      name: '猛毒「毒蛾の暗闇演舞」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: false,
    },
    {
      sub: 38,
      id: 19,
      name: '毒符「毒蛾の鱗粉」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: false,
    },
    {
      sub: 38,
      id: 20,
      name: '猛毒「毒蛾の暗闇演舞」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: false,
    },
    {
      sub: 44,
      id: 21,
      name: '鷹符「イルスタードダイブ」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: false,
    },
    {
      sub: 44,
      id: 22,
      name: '鷹符「イルスタードダイブ」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: false,
    },
    {
      sub: 44,
      id: 23,
      name: '鷹符「イルスタードダイブ」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: false,
    },
    {
      sub: 44,
      id: 24,
      name: '鷹符「イルスタードダイブ」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: false,
    },
    {
      sub: 52,
      id: 25,
      name: '夜盲「夜雀の歌」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: false,
    },
    {
      sub: 52,
      id: 26,
      name: '夜盲「夜雀の歌」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: false,
    },
    {
      sub: 52,
      id: 27,
      name: '夜盲「夜雀の歌」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: false,
    },
    {
      sub: 52,
      id: 28,
      name: '夜盲「夜雀の歌」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: false,
    },
    {
      sub: 58,
      id: 29,
      name: '夜雀「真夜中のコーラスマスター」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: true,
    },
    {
      sub: 58,
      id: 30,
      name: '夜雀「真夜中のコーラスマスター」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: true,
    },
    {
      sub: 58,
      id: 31,
      name: '夜雀「真夜中のコーラスマスター」',
      owner: 'ミスティア・ローレライ',
      face: 0,
      bonus: 15000000,
      lastSpell: true,
    },
  ],
  scripts: SCRIPTS,
  waves: ECL_FILE,
};
