// Auto-generated facade for ecldata4a.ecl by tools/th08/ecl.
// Do not edit directly; change the translator and run `npm run ecl:th08`.
//
// 61 subs, 2 timeline(s), 23 spell cards
// declared by op 122, 3 of them final spells per g_LastSpellNumbers.

import type { StageScript } from '../StageScript';
import * as SCRIPTS from './scripts';
import { ECL_FILE } from './waves';

export const STAGE4A_SCRIPT: StageScript = {
  route: 'stage4a',
  source: 'ecldata4a.ecl',
  subCount: 61,
  timelineCount: 2,
  cards: [
    {
      sub: 28,
      id: 54,
      name: '夢符「二重結界」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 28,
      id: 55,
      name: '夢符「二重結界」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 28,
      id: 56,
      name: '夢境「二重大結界」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 28,
      id: 57,
      name: '夢境「二重大結界」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 30,
      id: 58,
      name: '霊符「夢想封印　散」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 30,
      id: 59,
      name: '霊符「夢想封印　散」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 30,
      id: 60,
      name: '散霊「夢想封印　寂」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 30,
      id: 61,
      name: '散霊「夢想封印　寂」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 33,
      id: 62,
      name: '夢符「封魔陣」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 33,
      id: 63,
      name: '夢符「封魔陣」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 33,
      id: 64,
      name: '神技「八方鬼縛陣」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 33,
      id: 65,
      name: '神技「八方龍殺陣」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 41,
      id: 66,
      name: '霊符「夢想封印　集」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 41,
      id: 67,
      name: '霊符「夢想封印　集」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 41,
      id: 68,
      name: '回霊「夢想封印　侘」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 41,
      id: 69,
      name: '回霊「夢想封印　侘」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 22000000,
      lastSpell: false,
    },
    {
      sub: 46,
      id: 70,
      name: '境界「二重弾幕結界」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 25000000,
      lastSpell: false,
    },
    {
      sub: 46,
      id: 71,
      name: '境界「二重弾幕結界」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 25000000,
      lastSpell: false,
    },
    {
      sub: 46,
      id: 72,
      name: '大結界「博麗弾幕結界」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 25000000,
      lastSpell: false,
    },
    {
      sub: 46,
      id: 73,
      name: '大結界「博麗弾幕結界」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 25000000,
      lastSpell: false,
    },
    {
      sub: 54,
      id: 74,
      name: '神霊「夢想封印　瞬」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 25000000,
      lastSpell: true,
    },
    {
      sub: 54,
      id: 75,
      name: '神霊「夢想封印　瞬」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 25000000,
      lastSpell: true,
    },
    {
      sub: 54,
      id: 76,
      name: '神霊「夢想封印　瞬」',
      owner: '博麗霊夢',
      face: 0,
      bonus: 25000000,
      lastSpell: true,
    },
  ],
  scripts: SCRIPTS,
  waves: ECL_FILE,
};
