// Auto-generated facade for ecldata8.ecl by tools/th08/ecl.
// Do not edit directly; change the translator and run `npm run ecl:th08`.
//
// 156 subs, 2 timeline(s), 14 spell cards
// declared by op 122, 1 of them final spells per g_LastSpellNumbers.

import type { StageScript } from '../StageScript';
import * as SCRIPTS from './scripts';
import { ECL_FILE } from './waves';

export const EXTRA_SCRIPT: StageScript = {
  route: 'extra',
  source: 'ecldata8.ecl',
  subCount: 156,
  timelineCount: 2,
  cards: [
    {
      sub: 51,
      id: 191,
      name: '旧史「旧秘境史　-オールドヒストリー-」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 40000000,
      lastSpell: false,
    },
    {
      sub: 56,
      id: 192,
      name: '転世「一条戻り橋」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 40000000,
      lastSpell: false,
    },
    {
      sub: 60,
      id: 193,
      name: '新史「新幻想史　-ネクストヒストリー-」',
      owner: '上白沢慧音',
      face: 0,
      bonus: 40000000,
      lastSpell: false,
    },
    {
      sub: 93,
      id: 194,
      name: '時効「月のいはかさの呪い」',
      owner: '藤原妹紅',
      face: 0,
      bonus: 45000000,
      lastSpell: false,
    },
    {
      sub: 97,
      id: 195,
      name: '不死「火の鳥　-鳳翼天翔-」',
      owner: '藤原妹紅',
      face: 0,
      bonus: 45000000,
      lastSpell: false,
    },
    {
      sub: 100,
      id: 196,
      name: '藤原「滅罪寺院傷」',
      owner: '藤原妹紅',
      face: 0,
      bonus: 45000000,
      lastSpell: false,
    },
    {
      sub: 103,
      id: 197,
      name: '不死「徐福時空」',
      owner: '藤原妹紅',
      face: 0,
      bonus: 45000000,
      lastSpell: false,
    },
    {
      sub: 108,
      id: 198,
      name: '滅罪「正直者の死」',
      owner: '藤原妹紅',
      face: 0,
      bonus: 45000000,
      lastSpell: false,
    },
    {
      sub: 113,
      id: 199,
      name: '虚人「ウー」',
      owner: '藤原妹紅',
      face: 0,
      bonus: 45000000,
      lastSpell: false,
    },
    {
      sub: 118,
      id: 200,
      name: '不滅「フェニックスの尾」',
      owner: '藤原妹紅',
      face: 0,
      bonus: 45000000,
      lastSpell: false,
    },
    {
      sub: 126,
      id: 201,
      name: '蓬莱「凱風快晴　-フジヤマヴォルケイノ-」',
      owner: '藤原妹紅',
      face: 0,
      bonus: 45000000,
      lastSpell: false,
    },
    {
      sub: 131,
      id: 202,
      name: '「パゼストバイフェニックス」',
      owner: '藤原妹紅',
      face: 0,
      bonus: 10000000,
      lastSpell: false,
    },
    {
      sub: 143,
      id: 203,
      name: '「蓬莱人形」',
      owner: '藤原妹紅',
      face: 0,
      bonus: 45000000,
      lastSpell: false,
    },
    {
      sub: 149,
      id: 204,
      name: '「インペリシャブルシューティング」',
      owner: '藤原妹紅',
      face: 0,
      bonus: 10000000,
      lastSpell: true,
    },
  ],
  scripts: SCRIPTS,
  waves: ECL_FILE,
};
