import { existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { buildTaiseiAssets } from './art/taisei.mjs';

const ROOT = process.cwd();
const assets = buildTaiseiAssets(ROOT);

/** Playable team -> Taisei ship sprite. Teams with no upstream art keep the procedural painter. */
const PLAYER_CHARACTERS = {
  'reimu-yukari': 'reimu',
  'marisa-alice': 'marisa',
  'youmu-yuyuko': 'youmu',
};

// Single-frame sheets that are not part of a .frameNNNN sequence (e.g. enemy/swirl.png).
const dir = join(ROOT, 'public', 'assets', 'taisei');
for (const [ns, sub] of [['player', 'player'], ['enemy', 'enemy'], ['boss', 'boss']]) {
  const full = join(dir, sub);
  if (!existsSync(full)) continue;
  for (const f of readdirSync(full)) {
    if (!/\.(png|webp)$/.test(f) || f.includes('.frame')) continue;
    assets.textures['taisei:' + ns + ':' + f.replace(/\.[a-z]+$/, '')] = '/assets/taisei/' + sub + '/' + f;
  }
}

const sorted = Object.fromEntries(Object.entries(assets.textures).sort((a, b) => a[0].localeCompare(b[0])));
const lines = [
  '/* AUTO-GENERATED by tools/build-taisei.mjs from vendored Taisei art - do not edit by hand. */',
  '/* Taisei sprites (c) Taisei Project, CC-BY-SA 4.0 - see public/assets/taisei/COPYING.txt */',
  '',
  'export interface TaiseiAnimGroup {',
  '  /** Frame indices into the sprite sheet, in playback order. */',
  '  frames: number[];',
  '  /** Frames held per animation step. */',
  '  delay: number;',
  '  /** True when Taisei draws the group horizontally mirrored. */',
  '  mirror: boolean;',
  '}',
  '',
  'export type TaiseiAnim = Record<string, TaiseiAnimGroup>;',
  '',
  '/** Every vendored Taisei texture, keyed as taisei:<kind>:<name>[:frameNNNN]. */',
  'export const TAISEI_TEXTURES: Record<string, string> = {',
];
for (const [k, v] of Object.entries(sorted)) lines.push('  ' + JSON.stringify(k) + ': ' + JSON.stringify(v) + ',');
lines.push('};', '');
lines.push('/** Animation groups parsed from the upstream .ani files. */');
lines.push('export const TAISEI_ANIM: Record<string, TaiseiAnim> = {');
for (const [k, v] of Object.entries(assets.anim)) lines.push('  ' + JSON.stringify(k) + ': ' + JSON.stringify(v) + ',');
lines.push('};', '');
lines.push('/** Taisei sprite name per playable character (teams without upstream art stay procedural). */');
lines.push('export const TAISEI_PLAYER_BY_CHARACTER: Record<string, string> = {');
for (const [character, sheet] of Object.entries(PLAYER_CHARACTERS)) {
  if (assets.playerByName[sheet]) lines.push('  ' + JSON.stringify(character) + ': ' + JSON.stringify(sheet) + ',');
}
lines.push('};');
lines.push('');
lines.push('/** Taisei enemy sheet per stage spriteKey. */');
lines.push('export const TAISEI_ENEMY_BY_SPRITEKEY: Record<string, string> = {');
lines.push('  lumiaFairy: "fairy_blue",');
lines.push('  fairy: "fairy_red",');
lines.push('  rigelFairy: "bigfairy",');
lines.push('  cloudFairy: "hugefairy",');
lines.push('  sangFairy: "superfairy",');
lines.push('};', '');
lines.push('/** Taisei boss sheet per boss spriteKey (missing bosses keep the procedural painter). */');
lines.push('export const TAISEI_BOSS_BY_SPRITEKEY: Record<string, string> = {');
for (const b of Object.keys(assets.bossByName)) {
  if (b === 'iku_mid') continue;
  lines.push('  ' + JSON.stringify(b) + ': ' + JSON.stringify(b) + ',');
}
lines.push('};', '');
lines.push('/** Uniform on-screen scale: Taisei art is authored for a 640x480 viewport. */');
lines.push('export const TAISEI_SCALE = 0.6;');
lines.push('');
const out = join(ROOT, 'src', 'games', 'th08', 'data', 'taisei-assets.ts');
const { writeFileSync } = await import('node:fs');
writeFileSync(out, lines.join('\n'));
console.log('wrote', out, Object.keys(sorted).length, 'textures,', Object.keys(assets.anim).length, 'anim sets');
