// Regenerate src/games/th08/data/th08-hud-sprites.ts from the extracted ANM manifest.
//
// Rects come from the retail sheets; the coordinates the HUD draws them at live in
// th08-hud-layout.ts, which mirrors Gui::DrawGameScene in the decompilation.
import fs from 'node:fs';

const BQ = String.fromCharCode(96);
const manifestPath = 'public/assets/th08/manifest.json';
const outPath = 'src/games/th08/data/th08-hud-sprites.ts';
const m = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
const front = m.anm.front;
const ascii = m.anm.ascii;

const rect = (s) => `  ${s.id}: { x: ${s.x}, y: ${s.y}, w: ${s.w}, h: ${s.h} },`;
const frontRows = front.sprites.filter((s) => s.id <= 15).map(rect);
const asciiSprites = ascii.sprites.filter(
  (s) => s.id >= 31 && s.id <= 126 && s.w === 16 && s.h === 16,
);
const gaugeSprites = ascii.sprites.filter((s) => s.id >= 152 && s.id <= 156);
// Entry 2 carries the panel furniture: id 282 is the 符卡 indicator `Gui.cpp:1415-1419`
// parks at (488, 88), ids 283-287 the difficulty badges `Gui.cpp:2240-2245` picks as
// `difficulty + 283` for `ascii.anm` script 25, and 288 the spell-practice variant.
const badgeSprites = ascii.sprites.filter((s) => s.id >= 282 && s.id <= 288);
// Ids 0..30 are the 8x8 score-popup font in three banks: `AsciiManager.cpp:1639-1649`
// draws `digit`, then `digit + 11`, then `digit + 21` as the popup ages past 52 and 56
// frames. Id 10 is the 48x8 火力 marker that `CreateScorePopup(-1)` prints.
const popupSprites = ascii.sprites.filter((s) => s.id <= 30 && s.h === 8);

// Backticks in the doc block are spliced in afterwards so this file stays free of
// nested template escaping.
const out = `/**
 * HUD art rects from the original @front.anm@ and @ascii.anm@ sheets.
 * Auto-generated by @tools/gen-hud.mjs@ from public/assets/th08/manifest.json.
 *
 * @front@ entry 0 is the panel: id 0 is the 永夜抄 logo plate, ids 2-9 the row
 * labels in retail order (HiScore, Score, Player, Spell, Power, Graze, Point,
 * Time), ids 11/12 the life/bomb stars, id 13 the 32x32 backdrop tile.
 *
 * @ascii@ carries the 16x16 game font contiguously from id 31, which is U+0020.
 * @AsciiManager.cpp:483@ indexes it as @char + (31 - ' ')@, so glyph id is
 * @charCode - 1@ and the advance is @spaceWidth@ = 13, not the 16 of the cell.
 * Ids 152-156 are the 妖率計: 155 is the whole ornate track, 153/154 the 人/妖
 * limit icons.
 *
 * The badges live on @ascii@ entry 2 (@ascii_t2.png@), not the font page.
 */

export interface HudRect {
  x: number;
  y: number;
  w: number;
  h: number;
}

export const TH08_FRONT_ATLAS = '/assets/th08/anm/front_t0.png';
export const TH08_ASCII_ATLAS = '/assets/th08/anm/ascii_t0.png';
export const TH08_ASCII2_ATLAS = '/assets/th08/anm/ascii_t2.png';

/** First code point the 16x16 font covers (a space). */
export const ASCII_FIRST_GLYPH = 0x20;
/** Number of code points in the contiguous run, i.e. 0x20..0x7F. */
export const ASCII_GLYPH_COUNT = ${asciiSprites.length};
export const asciiGlyphId = (code: number): number => code - 1;

export const TH08_FRONT_RECTS: Record<number, HudRect> = {
${frontRows.join('\n')}
};

export const TH08_ASCII_RECTS: Record<number, HudRect> = {
${asciiSprites.map(rect).join('\n')}
};

/** 妖率計 pieces, by @ascii.anm@ sprite id. */
export const TH08_GAUGE_RECTS: Record<number, HudRect> = {
${gaugeSprites.map(rect).join('\n')}
};

/** Difficulty / 符卡 badges, by @ascii.anm@ sprite id (entry 2). */
export const TH08_BADGE_RECTS: Record<number, HudRect> = {
${badgeSprites.map(rect).join('\n')}
};

/** Score-popup glyphs, by @ascii.anm@ sprite id (three 11-cell banks). */
export const TH08_POPUP_RECTS: Record<number, HudRect> = {
${popupSprites.map(rect).join('\n')}
};
`;

const text = out.replace(/@([^@\n]+)@/g, (_all, inner) => BQ + inner + BQ);
fs.writeFileSync(outPath, text.replace(/\r\n/g, '\n'));
console.log(
  'front=' +
    frontRows.length +
    ' ascii=' +
    asciiSprites.length +
    ' gauge=' +
    gaugeSprites.length +
    ' badge=' +
    badgeSprites.length +
    ' popup=' +
    popupSprites.length,
);
