export type StageNumber = 1 | 2 | 3 | 4 | 5 | 6;
export type Difficulty = 'easy' | 'normal' | 'hard' | 'lunatic';
import { CHARACTER_PROFILES, type CharacterId, type CharacterProfile } from '../../touhou-common/player/CharacterProfile';
export { CHARACTER_PROFILES };
export type { CharacterId, CharacterProfile } from '../../touhou-common/player/CharacterProfile';
export declare const DIFFICULTY_MODIFIERS: Record<Difficulty, {
    label: string;
    bulletSpeed: number;
    bulletDensity: number;
    enemyHp: number;
    /**
     * Boss life-bar multiplier. Deliberately gentler than `enemyHp`: a boss already
     * gains an extra life on Hard/Lunatic, and stacking both would turn the last
     * cards into a minute-long grind.
     */
    bossHp: number;
}>;
export interface StageMetadata {
    stage: StageNumber;
    title: string;
    boss: string;
    theme: string;
    /** Parallax art set for the stage (see tools/art/backgrounds.mjs). */
    bgTheme: StageTheme;
    cycleFrames: number;
    /**
     * Ambient light on the painted backdrop. Every TH08 stage keeps one fixed
     * level for its whole length — the mood of the hour, not a day/night cycle.
     */
    bgBrightness: number;
    /** How fast the backdrop scrolls down, in playfield pixels per frame. */
    bgScroll: number;
}
export declare const STAGE_METADATA: Record<StageNumber, StageMetadata>;
/** Baked texture atlas: 213 PNGs generated by tools/generate-assets.mjs. */
export { ASSET_MANIFEST, BULLET_PALETTE, BULLET_SHAPE_KEYS, ASSET_KEYS } from './data/asset-manifest';
export type { AssetManifest } from '../../engine/renderer/AssetManager';
/** Background themes available in the atlas. */
export type StageTheme = 'forestNight' | 'lake' | 'nightSky' | 'village' | 'bambooMoon' | 'moonCity';
export declare const STAGE_THEMES: StageTheme[];
export declare function isStageNumber(value: number): value is StageNumber;
export declare function getCharacterProfile(id?: CharacterId): CharacterProfile;
//# sourceMappingURL=types.d.ts.map