/**
 * HUD art rects from the original `front.anm` and `ascii.anm` sheets.
 * Auto-generated by `tools/gen-hud.mjs` from public/assets/th08/manifest.json.
 *
 * `front` entry 0 is the panel: id 0 is the 永夜抄 logo plate, ids 2-9 the row
 * labels in retail order (HiScore, Score, Player, Spell, Power, Graze, Point,
 * Time), ids 11/12 the life/bomb stars, id 13 the 32x32 backdrop tile.
 *
 * `ascii` carries the 16x16 game font contiguously from id 31, which is U+0020.
 * `AsciiManager.cpp:483` indexes it as `char + (31 - ' ')`, so glyph id is
 * `charCode - 1` and the advance is `spaceWidth` = 13, not the 16 of the cell.
 * Ids 152-156 are the 妖率計: 155 is the whole ornate track, 153/154 the 人/妖
 * limit icons.
 *
 * The badges live on `ascii` entry 2 (`ascii_t2.png`), not the font page.
 */
export interface HudRect {
    x: number;
    y: number;
    w: number;
    h: number;
}
export declare const TH08_FRONT_ATLAS = "/assets/th08/anm/front_t0.png";
export declare const TH08_ASCII_ATLAS = "/assets/th08/anm/ascii_t0.png";
export declare const TH08_ASCII2_ATLAS = "/assets/th08/anm/ascii_t2.png";
/** First code point the 16x16 font covers (a space). */
export declare const ASCII_FIRST_GLYPH = 32;
/** Number of code points in the contiguous run, i.e. 0x20..0x7F. */
export declare const ASCII_GLYPH_COUNT = 96;
export declare const asciiGlyphId: (code: number) => number;
export declare const TH08_FRONT_RECTS: Record<number, HudRect>;
export declare const TH08_ASCII_RECTS: Record<number, HudRect>;
/** 妖率計 pieces, by `ascii.anm` sprite id. */
export declare const TH08_GAUGE_RECTS: Record<number, HudRect>;
/** Difficulty / 符卡 badges, by `ascii.anm` sprite id (entry 2). */
export declare const TH08_BADGE_RECTS: Record<number, HudRect>;
/** Score-popup glyphs, by `ascii.anm` sprite id (three 11-cell banks). */
export declare const TH08_POPUP_RECTS: Record<number, HudRect>;
//# sourceMappingURL=th08-hud-sprites.d.ts.map