/**
 * Register the cells the *ship's own* animation packs carry.
 *
 * `g_PlayerAnmFilenames` (`Player.cpp:44-47`) points every shot type at one of the
 * four `playerNN.anm` packs, and the same pack holds the shot sprites, the 式神 and
 * blade bodies, and the hit sparks - `FUN_0044fb70` runs a shot's script out of
 * `g_PlayerAnm`, not out of `etama.anm`. Those cells were never sliced, which is why
 * the ship's weapon has been drawing with invented art while the enemy bullets had
 * the real thing.
 *
 * The rectangles are retail's own, generated by `tools/th08/anm/generate-player.mjs`
 * from the manifest the extractor wrote, so nothing here is measured by eye.
 */
import type { PixiRenderer } from '../../../engine/renderer/PixiRenderer';
/** One drawn cell: `th08:pshot:player01_t0:14` and friends. */
export declare function th08PlayerCellKey(team: number, page: number, sprite: number): string;
/** The pack a shot type draws from, i.e. `g_PlayerAnmFilenames[shotType]`. */
export declare function th08PlayerAnmTeam(shotType: number): number;
/**
 * Slice and register every cell of the four packs. Returns how many cells landed;
 * a zero means the extracted pages are not in place, which is when the fallback
 * bullet art has to keep working.
 */
export declare function registerTH08PlayerCells(renderer: PixiRenderer): Promise<number>;
/** The cell box a sprite id occupies in a pack, for a host that sizes its own quad. */
export declare function th08PlayerCellSize(team: number, sprite: number): {
    w: number;
    h: number;
} | null;
//# sourceMappingURL=th08-player-shot-registration.d.ts.map