/**
 * Generated by tools/th08/anm/generate-effects.mjs from effect-templates.ref.json and
 * public/assets/th08/manifest.json (etama.anm). Do not edit by hand.
 *
 * The retail effect template table plus the untouched ANM bytecode of every script it
 * can name. Effect ids in ECL (ops 128/139/140/174) are template ids, not script ids;
 * `EFFECT_TEMPLATES[id]` is the translation between them.
 */
/**
 * Decompile names for the two callbacks a template can carry.
 *
 * The update runs every frame before the script and retires the effect when it stops
 * returning 1; the init runs once on the spawn frame and fails the spawn when it returns
 * non-zero (`EffectManager.cpp:157-170`, `:1090-1105`).
 */
export type EffectBehavior = 'AnmVmUpdate0040eb50' | 'EffectOrbitInit' | 'EffectOrbitUpdate' | 'EffectRandomSplashBigInit' | 'EffectRandomSplashInit' | 'EffectRandomSplashUpdate' | 'FUN_0040e040' | 'FUN_0040e120' | 'FUN_0040e200' | 'FUN_0040e2d0' | 'FUN_00410bb0' | 'FUN_004114e0' | 'FUN_00411720' | 'FUN_00411a80' | 'FUN_00413070' | 'FUN_00426280' | 'FUN_004264f0' | 'FUN_00426720' | 'FUN_00426990' | 'FUN_00426b20' | 'FUN_00426bb0' | 'FUN_00426c40' | 'FUN_00426c90' | 'FUN_00426d70' | 'FUN_00426e70' | 'FUN_004270c0' | 'FUN_004271a0' | 'FUN_00427250' | 'FUN_00427260' | 'FUN_004272e0' | 'FUN_00427970' | 'FUN_00427990' | 'FUN_004279d0' | 'FUN_00427a60' | 'FUN_00427ae0' | 'FUN_00427b50';
/** One row of `g_EffectTemplates`. */
export interface EffectTemplate {
    /** Script index inside `etama.anm` (`EffectManager.cpp:157`). */
    readonly scriptIdx: number;
    /** Per-frame mover, run before the ANM script. */
    readonly update: EffectBehavior | null;
    /** One-shot spawn setup, run after the script was attached. */
    readonly init: EffectBehavior | null;
}
/** Effect id -> template, indexed exactly like the retail array. */
export declare const EFFECT_TEMPLATES: readonly EffectTemplate[];
/**
 * `etama.anm` script words, base64, indexed by retail script number.
 *
 * Every one of the 116 scripts is lifted: the templates already cover 56 of them and
 * the bullet system may want the rest, while the whole pack is only kilobytes.
 */
export declare const TH08_EFFECT_SCRIPT_BYTES: readonly (string | null)[];
/** Script words for one template id, or null when the pack is not loaded. */
export declare function effectScriptBytes(id: number): string | null;
//# sourceMappingURL=th08-effect-anm.d.ts.map